title: "Ruby Ahlvin â€“ Data Science Projects"
description: "Psychology & Statistics student exploring human learning, behavior, and development through data analysis and statistical modeling"
theme: jekyll-theme-cayman
